# Generated by Django 3.0.5 on 2020-09-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20200902_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_extract',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
